package de.greenrobot.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daoexample.Note;
import de.greenrobot.daoexample.Country;
import de.greenrobot.daoexample.Link;

import de.greenrobot.daoexample.NoteDao;
import de.greenrobot.daoexample.CountryDao;
import de.greenrobot.daoexample.LinkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig linkDaoConfig;

    private final NoteDao noteDao;
    private final CountryDao countryDao;
    private final LinkDao linkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        linkDaoConfig = daoConfigMap.get(LinkDao.class).clone();
        linkDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        linkDao = new LinkDao(linkDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Country.class, countryDao);
        registerDao(Link.class, linkDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        countryDaoConfig.getIdentityScope().clear();
        linkDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public LinkDao getLinkDao() {
        return linkDao;
    }

}
